name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: pip install -e .[lint]
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files --verbose
      - name: Run mypy
        run: bash scripts/lint.sh

  tests:

    name: test py${{ matrix.python-version }} on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}-latest


    strategy:

      matrix:

        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

        os: [ubuntu, macos, windows]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: pip install -e .[test]

      - name: Freeze Dependencies
        run: pip freeze

      - name: Test with pytest
        run: bash scripts/test.sh

      - name: Upload coverage
        uses: codecov/codecov-action@v4

  # https://github.com/marketplace/actions/alls-green#why used for branch protection checks
  check:
    if: always()
    needs: [lint, tests]
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
