name: Lint and Format

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: pip install -e .[lint]
      - name: Lint
        run: bash scripts/format.sh
      - name: check Static Analysis
        run: bash scripts/lint.sh
