name: Publish

on:
  release:
    types:
      - created

jobs:

  release:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: check version
        id: check-tag
        uses: samuelcolvin/check-python-version@v4.1
        with:
          version_file_path: fastapi_class/__init__.py

      - name: build
        run: uv build

      - name: Upload package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
